version: '3.5'
services:
    backend:
        image: makabea-backend
        ports:
            - "80:80"
    database:
        image: makabea-db
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: makabea
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        volumes:
            db-volume:/var/lib/mysql
volumes:
    db-volume: